---
title: Siteleaf Setting
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: This site was created so I can get used with siteleaf.
baseurl: 
url: 
twitter_username: "@siteleaf"
github_username: siteleaf
theme: minima
plugins:
- jekyll-feed
